### ISSUE TITLE
🚨  SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (7:7)

### ISSUE THREAD

**Issue by davidmoshal** [vuese/vuese#29]
**Describe the bug**

```
vuese gen --include="src/apps/book/BookApp.vue"

🚨  The error occurred when processing:<path>/Book.demo.vue
🚨  SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (7:7)
    at _class.raise (<home>/.nvm/versions/node/v10.13.0/lib/node_modules/vuese/node_modules/@babel/parser/lib/index.js:4051:15)
    at _class.expectPlugin (<home>/.nvm/versions/node/v10.13.0/lib/node_modules/vuese/node_modules/@babel/parser/lib/index.js:5387:18)
```

**To Reproduce**

This is the Vue file:

```vue
<template>
  <div>
    Book demo
  </div>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator'

  @Component
  export default class BookDemo extends Vue {

    name = 'Book.demo.vue'
  }
</script>

<style scoped>

</style>
```

**Expected behavior**
No Error

**Comment by davidmoshal** [comment]
Tried advice here: https://github.com/babel/babel/issues/8655

specifically:
`npm i -D @babel/plugin-proposal-class-properties`

```js
// .babel.config.js

module.exports = {
  presets: [
    '@vue/app'
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
  ]
}
```

but to no avail.

**Comment by HcySunYang** [comment]
I have fixed this issue in version 1.4.7. In fact, you can support the features you want by adding the `babelParserPlugins` configuration item to `.vueserc`.E.g:
```js
// .vueserc
{
  "include": ["**/*.vue"],
  "babelParserPlugins": [
       'objectRestSpread',
        'dynamicImport',
        'decorators-legacy',
        'classProperties',
        'typescript'
  ]
}
```
Note: `babelParserPlugins` overrides the default value, so when you add a new plugin you need to include the plugin supported by default above. see the list of all plugins: https://babeljs.io/docs/en/babel-parser#plugins

**Comment by HcySunYang** [comment]
For 1: 
The above ·`.vuese` configuration is what I used to explain to you how to support `classProperties ` in versions 1.4.6 and earlier. So in version 1.4.7 you don't need to manually configure these.
If a component does not have any events, props, slots, and methods, then this component will not generate anything (Related: https://github.com/vuese/vuese/issues/18), check your components?

For 2:
The `vuese gen` command has two options: `docute` or `markdown`. Can `markdown` meet your needs?

For 3:
a) & b) You don't need to add anything to `.babel.config.js`. 
c) No, The babel plugin is not equal to the babel parser plugin. The babel parser plugin only has these options: https://babeljs.io/docs/en/babel-parser#plugins.
The list of plugins currently provided by vuese for babel parser is:
```js
'objectRestSpread',
'dynamicImport',
'decorators-legacy',
'classProperties',
'typescript'
```
Can see the code here: https://github.com/vuese/vuese/blob/master/src/parser/sfcToAST.ts#L21-L27

**Comment by davidmoshal** [comment]
> For 1:
> The above ·`.vuese` configuration is what I used to explain to you how to support `classProperties ` in versions 1.4.6 and earlier. So in version 1.4.7 you don't need to manually configure these.

Confirmed that the 1.4.7 doesn't cause errors, with:
- no `.vueserc`, 
- no changes to `.babel.config.js`, and
- no other modules added to npm.

> If a component does not have any events, props, slots, and methods, then this component will not generate anything (Related: #18), check your components?

Still not generating anything, eg for a component like this:
```vue
<template>
  <div>
    Book demo
  </div>
</template>

<script lang="ts">
  import { Component, Prop, Vue } from "vue-property-decorator"

  @Component
  export default class BookDemo extends Vue {

    @Prop()
    name = 'Book.demo.vue'

    method1(){
      console.log('method1')
    }
  }
</script>

<style scoped>

</style>
```

 
> For 2:
> The `vuese gen` command has two options: `docute` or `markdown`. Can `markdown` meet your needs?

Probably, but it's not generating anything at the moment, so can't be sure.
